version from __init__.py
t0xic0der/supervisor-frontend-service pull request #97
Opened 2021-05-13 17:20 UTC by sachindavra

Signed-off-by: sachindavra <raju.davra@gmail.com>

2021-05-13 17:20 UTC, sachindavra commented
Kindly try running it and let me know in case modification is required.

2021-05-14 16:36 UTC, t0xic0der requested changes
Please make the necessary changes to use the already imported version variable.

2021-05-14 16:36 UTC, t0xic0der commented on src/svfrontend/main.py
> +@click.version_option(__version__="1.1.0-beta", prog_name=click.style("SuperVisor Frontend Service", fg="magenta"))
There is no point in importing the `__version__` variable from the `__init__.py` file if it is being reassigned to a new value here. The version number is, hence, still hardcoded. Please make the necessary changes.

2021-05-14 16:36 UTC, t0xic0der commented on src/svfrontend/main.py
> +from __init__ import __version__
You need not import the `__version__` variable again as it has been imported already in the code via the lines from 38 to 43.

2021-05-15 05:23 UTC, sachindavra commented
Hi @t0xic0der, thanks for guidance. 
I have made the changes and created pull request. Please check and let me know if still changes are required.

2021-05-15 05:35 UTC, t0xic0der requested changes
Kindly make the requested changes. :)

2021-05-15 05:35 UTC, t0xic0der commented on src/svfrontend/main.py
> +@click.version_option(version=__version__, prog_name=click.style("SuperVisor Frontend Service", fg="magenta"))
Please change this to the following code, as the `__version__` variable has been imported from the `__init__.py` file as `frntvers`.

```suggestion
@click.version_option(version=frntvers, prog_name=click.style("SuperVisor Frontend Service", fg="magenta"))
```

2021-05-15 06:06 UTC, sachindavra commented on src/svfrontend/main.py
> +@click.version_option(version=__version__, prog_name=click.style("SuperVisor Frontend Service", fg="magenta"))
Thanks for suggesting the changes. 
I have made the changes and raise a pull request. Please review it and let me know if changes are required anymore.

2021-05-15 11:21 UTC, t0xic0der approved these changes
I am merging this PR now.

As the commit messages were not accurately representing the changes which took place in them and just because the scope of this PR is limited, I would squash the commits into one and merge them.

Thanks for contributing. Feel free to star the repo if you found it useful.

2021-05-15 11:21 UTC, t0xic0der commented on src/svfrontend/main.py
> +@click.version_option(version=frntvers, prog_name=click.style("SuperVisor Frontend Service", fg="magenta"))
LGTM. :+1:

2021-05-15 11:22 UTC, merged